language: node_js
node_js:
  - "8.11.0"
before_deploy: "echo 'Deploying new npm package'"
deploy:
  provider: npm
  email: smcelhinney@hubspot.com
  api_key: $NPM_TOKEN
  on:
    branch: release
    repo: HubSpotWebTeam/hs-node-api
